// <auto-generated />
using System;
using CCMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260108070720_FilterUniqueIndexForOwnerContent")]
    partial class FilterUniqueIndexForOwnerContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CCMS.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreativeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DailySlotAssignmentsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveredImpressions")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpectedImpressions")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SlotNumbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreativeId");

                    b.HasIndex("ScreenId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdvertiserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Creative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("LockedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Creatives");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Impression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreativeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<Guid?>("OwnerContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SlotPosition")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreativeId");

                    b.HasIndex("OwnerContentId");

                    b.HasIndex("BookingId", "SessionDate")
                        .HasDatabaseName("IX_Impressions_Booking_SessionDate");

                    b.HasIndex("CampaignId", "PlayedAt")
                        .HasDatabaseName("IX_Impressions_Campaign_PlayedAt");

                    b.HasIndex("ScreenId", "PlayedAt")
                        .HasDatabaseName("IX_Impressions_Screen_PlayedAt");

                    b.ToTable("Impressions");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId", "OrganizationId")
                        .IsUnique();

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.OwnerContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PricePerPlay")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ScreenId", "SlotNumber")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("OwnerContents");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Screen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKeyHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectedDeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DefaultVideoSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DefaultVideoUploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultVideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DimensionUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasCustomDefaultVideo")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxViewers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PhysicalHeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PhysicalWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerSlot")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ResolutionHeight")
                        .HasColumnType("int");

                    b.Property<int>("ResolutionWidth")
                        .HasColumnType("int");

                    b.Property<int>("SlotsPerFrame")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TimeFrameMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Screens");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.SlotAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookedSlots")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SlotBookings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ScreenId", "Date")
                        .IsUnique();

                    b.ToTable("SlotAvailabilities", t =>
                        {
                            t.HasCheckConstraint("CK_SlotAvailability_BookedSlotsNonNegative", "[BookedSlots] >= 0");

                            t.HasCheckConstraint("CK_SlotAvailability_BookedSlotsNotExceedTotal", "[BookedSlots] <= [TotalSlots]");
                        });
                });

            modelBuilder.Entity("CCMS.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Booking", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Bookings")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCMS.Domain.Entities.Creative", "Creative")
                        .WithMany("Bookings")
                        .HasForeignKey("CreativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCMS.Domain.Entities.Screen", "Screen")
                        .WithMany("Bookings")
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Creative");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.User", "Advertiser")
                        .WithMany("Campaigns")
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertiser");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Creative", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Creatives")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Impression", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.Booking", "Booking")
                        .WithMany("Impressions")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCMS.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCMS.Domain.Entities.Creative", "Creative")
                        .WithMany()
                        .HasForeignKey("CreativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCMS.Domain.Entities.OwnerContent", "OwnerContent")
                        .WithMany("Impressions")
                        .HasForeignKey("OwnerContentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CCMS.Domain.Entities.Screen", "Screen")
                        .WithMany("Impressions")
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Campaign");

                    b.Navigation("Creative");

                    b.Navigation("OwnerContent");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Membership", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.Organization", "Organization")
                        .WithMany("Memberships")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCMS.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Organization", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.OwnerContent", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Screen", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.User", "Owner")
                        .WithMany("Screens")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CCMS.Domain.ValueObjects.Address", "Location", b1 =>
                        {
                            b1.Property<Guid>("ScreenId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("ScreenId");

                            b1.ToTable("Screens");

                            b1.WithOwner()
                                .HasForeignKey("ScreenId");
                        });

                    b.OwnsOne("CCMS.Domain.ValueObjects.OperatingSchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("ScreenId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("ScreenId");

                            b1.ToTable("Screens");

                            b1.WithOwner()
                                .HasForeignKey("ScreenId");

                            b1.OwnsOne("CCMS.Domain.ValueObjects.DaySchedule", "Friday", b2 =>
                                {
                                    b2.Property<Guid>("OperatingScheduleScreenId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<TimeSpan>("EndTime")
                                        .HasColumnType("time");

                                    b2.Property<bool>("IsOperating")
                                        .HasColumnType("bit");

                                    b2.Property<TimeSpan>("StartTime")
                                        .HasColumnType("time");

                                    b2.HasKey("OperatingScheduleScreenId");

                                    b2.ToTable("Screens");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingScheduleScreenId");
                                });

                            b1.OwnsOne("CCMS.Domain.ValueObjects.DaySchedule", "Monday", b2 =>
                                {
                                    b2.Property<Guid>("OperatingScheduleScreenId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<TimeSpan>("EndTime")
                                        .HasColumnType("time");

                                    b2.Property<bool>("IsOperating")
                                        .HasColumnType("bit");

                                    b2.Property<TimeSpan>("StartTime")
                                        .HasColumnType("time");

                                    b2.HasKey("OperatingScheduleScreenId");

                                    b2.ToTable("Screens");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingScheduleScreenId");
                                });

                            b1.OwnsOne("CCMS.Domain.ValueObjects.DaySchedule", "Saturday", b2 =>
                                {
                                    b2.Property<Guid>("OperatingScheduleScreenId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<TimeSpan>("EndTime")
                                        .HasColumnType("time");

                                    b2.Property<bool>("IsOperating")
                                        .HasColumnType("bit");

                                    b2.Property<TimeSpan>("StartTime")
                                        .HasColumnType("time");

                                    b2.HasKey("OperatingScheduleScreenId");

                                    b2.ToTable("Screens");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingScheduleScreenId");
                                });

                            b1.OwnsOne("CCMS.Domain.ValueObjects.DaySchedule", "Sunday", b2 =>
                                {
                                    b2.Property<Guid>("OperatingScheduleScreenId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<TimeSpan>("EndTime")
                                        .HasColumnType("time");

                                    b2.Property<bool>("IsOperating")
                                        .HasColumnType("bit");

                                    b2.Property<TimeSpan>("StartTime")
                                        .HasColumnType("time");

                                    b2.HasKey("OperatingScheduleScreenId");

                                    b2.ToTable("Screens");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingScheduleScreenId");
                                });

                            b1.OwnsOne("CCMS.Domain.ValueObjects.DaySchedule", "Thursday", b2 =>
                                {
                                    b2.Property<Guid>("OperatingScheduleScreenId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<TimeSpan>("EndTime")
                                        .HasColumnType("time");

                                    b2.Property<bool>("IsOperating")
                                        .HasColumnType("bit");

                                    b2.Property<TimeSpan>("StartTime")
                                        .HasColumnType("time");

                                    b2.HasKey("OperatingScheduleScreenId");

                                    b2.ToTable("Screens");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingScheduleScreenId");
                                });

                            b1.OwnsOne("CCMS.Domain.ValueObjects.DaySchedule", "Tuesday", b2 =>
                                {
                                    b2.Property<Guid>("OperatingScheduleScreenId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<TimeSpan>("EndTime")
                                        .HasColumnType("time");

                                    b2.Property<bool>("IsOperating")
                                        .HasColumnType("bit");

                                    b2.Property<TimeSpan>("StartTime")
                                        .HasColumnType("time");

                                    b2.HasKey("OperatingScheduleScreenId");

                                    b2.ToTable("Screens");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingScheduleScreenId");
                                });

                            b1.OwnsOne("CCMS.Domain.ValueObjects.DaySchedule", "Wednesday", b2 =>
                                {
                                    b2.Property<Guid>("OperatingScheduleScreenId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<TimeSpan>("EndTime")
                                        .HasColumnType("time");

                                    b2.Property<bool>("IsOperating")
                                        .HasColumnType("bit");

                                    b2.Property<TimeSpan>("StartTime")
                                        .HasColumnType("time");

                                    b2.HasKey("OperatingScheduleScreenId");

                                    b2.ToTable("Screens");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingScheduleScreenId");
                                });

                            b1.Navigation("Friday")
                                .IsRequired();

                            b1.Navigation("Monday")
                                .IsRequired();

                            b1.Navigation("Saturday")
                                .IsRequired();

                            b1.Navigation("Sunday")
                                .IsRequired();

                            b1.Navigation("Thursday")
                                .IsRequired();

                            b1.Navigation("Tuesday")
                                .IsRequired();

                            b1.Navigation("Wednesday")
                                .IsRequired();
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("CCMS.Domain.Entities.SlotAvailability", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Impressions");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Creatives");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Creative", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.OwnerContent", b =>
                {
                    b.Navigation("Impressions");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Screen", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Impressions");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.User", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("Memberships");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Screens");
                });
#pragma warning restore 612, 618
        }
    }
}
