// <auto-generated />
using System;
using CCMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CCMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204101511_DateOnlyAndIndiaDefaults")]
    partial class DateOnlyAndIndiaDefaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CCMS.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DailySlotAssignmentsJson")
                        .HasColumnType("text");

                    b.Property<int>("DeliveredImpressions")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("ExpectedImpressions")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uuid");

                    b.Property<string>("SlotNumbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreativeId");

                    b.HasIndex("ScreenId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Creative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("LockedReason")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Creatives");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerificationTokens");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Impression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClientTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpectedDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("ImpressionId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OwnerContentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlayerVersion")
                        .HasColumnType("text");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SlotPlayKey")
                        .HasColumnType("text");

                    b.Property<int?>("SlotPosition")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationHash")
                        .HasColumnType("text");

                    b.Property<bool>("WasFullPlay")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreativeId");

                    b.HasIndex("OwnerContentId");

                    b.HasIndex("SessionDate")
                        .HasDatabaseName("IX_Impressions_SessionDate");

                    b.HasIndex("BookingId", "SessionDate")
                        .HasDatabaseName("IX_Impressions_Booking_SessionDate");

                    b.HasIndex("BookingId", "WasFullPlay")
                        .HasDatabaseName("IX_Impressions_Booking_WasFullPlay");

                    b.HasIndex("CampaignId", "PlayedAt")
                        .HasDatabaseName("IX_Impressions_Campaign_PlayedAt");

                    b.HasIndex("ScreenId", "PlayedAt")
                        .HasDatabaseName("IX_Impressions_Screen_PlayedAt");

                    b.ToTable("Impressions");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.ImpressionDailySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreativeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FirstPlayAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FullPlays")
                        .HasColumnType("integer");

                    b.Property<string>("HourlyPlays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastPlayAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OwnerContentId")
                        .HasColumnType("uuid");

                    b.Property<int>("PartialPlays")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TotalExpectedDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPlays")
                        .HasColumnType("integer");

                    b.Property<int>("UnverifiedPlays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VerifiedPlays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreativeId");

                    b.HasIndex("CampaignId", "Date")
                        .HasDatabaseName("IX_ImpressionDailySummaries_Campaign_Date");

                    b.HasIndex("OwnerContentId", "Date")
                        .HasDatabaseName("IX_ImpressionDailySummaries_OwnerContent_Date");

                    b.HasIndex("ScreenId", "Date")
                        .HasDatabaseName("IX_ImpressionDailySummaries_Screen_Date");

                    b.HasIndex("BookingId", "ScreenId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_ImpressionDailySummaries_Booking_Screen_Date");

                    b.ToTable("ImpressionDailySummaries");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId", "OrganizationId")
                        .IsUnique();

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.OwnerContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PricePerPlay")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ScreenId", "SlotNumber")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("OwnerContents");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.PhoneVerificationOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PhoneNumber", "CreatedAt");

                    b.ToTable("PhoneVerificationOtps");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Screen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .HasColumnType("text");

                    b.Property<string>("ConnectedDeviceId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("DefaultVideoSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DefaultVideoUploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultVideoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeviceBoundAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceFingerprintHash")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeviceOverrideAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeviceOverrideByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceOverrideReason")
                        .HasColumnType("text");

                    b.Property<string>("DimensionUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasCustomDefaultVideo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastDeviceVerification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastTaggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LastTaggedLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("LastTaggedLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("MaxViewers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PhysicalHeight")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("PhysicalWidth")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("PreviousDeviceFingerprintHash")
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerSlot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ResolutionHeight")
                        .HasColumnType("integer");

                    b.Property<int>("ResolutionWidth")
                        .HasColumnType("integer");

                    b.Property<int>("SlotsPerFrame")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TimeFrameMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_Screens_Owner");

                    b.HasIndex("PricePerSlot")
                        .HasDatabaseName("IX_Screens_Price");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Screens_Status");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("IX_Screens_Location");

                    b.ToTable("Screens");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.ScreenImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("ImageType")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScreenId")
                        .HasDatabaseName("IX_ScreenImages_Screen");

                    b.HasIndex("ScreenId", "ImageType")
                        .HasDatabaseName("IX_ScreenImages_Screen_Type");

                    b.HasIndex("ScreenId", "IsPrimary")
                        .HasDatabaseName("IX_ScreenImages_Screen_Primary");

                    b.ToTable("ScreenImages");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.ScreenTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("GooglePlaceTypes")
                        .HasColumnType("text");

                    b.Property<string>("IconName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemTag")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxDistanceMeters")
                        .HasColumnType("integer");

                    b.Property<int?>("MinPoiCount")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_ScreenTags_Category");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_ScreenTags_Slug");

                    b.ToTable("ScreenTags");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.ScreenTagAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DistanceMeters")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PoiCount")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("ScreenId")
                        .HasDatabaseName("IX_ScreenTagAssignments_Screen");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_ScreenTagAssignments_Tag");

                    b.HasIndex("ScreenId", "IsPrimary")
                        .HasDatabaseName("IX_ScreenTagAssignments_Screen_Primary");

                    b.HasIndex("ScreenId", "Source")
                        .HasDatabaseName("IX_ScreenTagAssignments_Screen_Source");

                    b.HasIndex("ScreenId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("IX_ScreenTagAssignments_Screen_Tag");

                    b.ToTable("ScreenTagAssignments");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.SlotAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BookedSlots")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uuid");

                    b.Property<string>("SlotBookings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ScreenId", "Date")
                        .IsUnique();

                    b.ToTable("SlotAvailabilities", t =>
                        {
                            t.HasCheckConstraint("CK_SlotAvailability_BookedSlotsNonNegative", "\"BookedSlots\" >= 0");

                            t.HasCheckConstraint("CK_SlotAvailability_BookedSlotsNotExceedTotal", "\"BookedSlots\" <= \"TotalSlots\"");
                        });
                });

            modelBuilder.Entity("CCMS.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredTimezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Booking", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Bookings")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCMS.Domain.Entities.Creative", "Creative")
                        .WithMany("Bookings")
                        .HasForeignKey("CreativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCMS.Domain.Entities.Screen", "Screen")
                        .WithMany("Bookings")
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Creative");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.User", "Advertiser")
                        .WithMany("Campaigns")
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertiser");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Creative", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Creatives")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.User", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Impression", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.Booking", "Booking")
                        .WithMany("Impressions")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CCMS.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CCMS.Domain.Entities.Creative", "Creative")
                        .WithMany()
                        .HasForeignKey("CreativeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CCMS.Domain.Entities.OwnerContent", "OwnerContent")
                        .WithMany("Impressions")
                        .HasForeignKey("OwnerContentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CCMS.Domain.Entities.Screen", "Screen")
                        .WithMany("Impressions")
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Campaign");

                    b.Navigation("Creative");

                    b.Navigation("OwnerContent");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.ImpressionDailySummary", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CCMS.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CCMS.Domain.Entities.Creative", "Creative")
                        .WithMany()
                        .HasForeignKey("CreativeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CCMS.Domain.Entities.OwnerContent", "OwnerContent")
                        .WithMany()
                        .HasForeignKey("OwnerContentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CCMS.Domain.Entities.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Campaign");

                    b.Navigation("Creative");

                    b.Navigation("OwnerContent");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Membership", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.Organization", "Organization")
                        .WithMany("Memberships")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCMS.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Organization", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.OwnerContent", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.PhoneVerificationOtp", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.User", "User")
                        .WithMany("PhoneVerificationOtps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Screen", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.User", "Owner")
                        .WithMany("Screens")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CCMS.Domain.ValueObjects.Address", "Location", b1 =>
                        {
                            b1.Property<Guid>("ScreenId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("ScreenId");

                            b1.ToTable("Screens");

                            b1.WithOwner()
                                .HasForeignKey("ScreenId");
                        });

                    b.OwnsOne("CCMS.Domain.ValueObjects.OperatingSchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("ScreenId")
                                .HasColumnType("uuid");

                            b1.HasKey("ScreenId");

                            b1.ToTable("Screens");

                            b1.WithOwner()
                                .HasForeignKey("ScreenId");

                            b1.OwnsOne("CCMS.Domain.ValueObjects.DaySchedule", "Friday", b2 =>
                                {
                                    b2.Property<Guid>("OperatingScheduleScreenId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeSpan>("EndTime")
                                        .HasColumnType("interval");

                                    b2.Property<bool>("IsOperating")
                                        .HasColumnType("boolean");

                                    b2.Property<TimeSpan>("StartTime")
                                        .HasColumnType("interval");

                                    b2.HasKey("OperatingScheduleScreenId");

                                    b2.ToTable("Screens");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingScheduleScreenId");
                                });

                            b1.OwnsOne("CCMS.Domain.ValueObjects.DaySchedule", "Monday", b2 =>
                                {
                                    b2.Property<Guid>("OperatingScheduleScreenId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeSpan>("EndTime")
                                        .HasColumnType("interval");

                                    b2.Property<bool>("IsOperating")
                                        .HasColumnType("boolean");

                                    b2.Property<TimeSpan>("StartTime")
                                        .HasColumnType("interval");

                                    b2.HasKey("OperatingScheduleScreenId");

                                    b2.ToTable("Screens");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingScheduleScreenId");
                                });

                            b1.OwnsOne("CCMS.Domain.ValueObjects.DaySchedule", "Saturday", b2 =>
                                {
                                    b2.Property<Guid>("OperatingScheduleScreenId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeSpan>("EndTime")
                                        .HasColumnType("interval");

                                    b2.Property<bool>("IsOperating")
                                        .HasColumnType("boolean");

                                    b2.Property<TimeSpan>("StartTime")
                                        .HasColumnType("interval");

                                    b2.HasKey("OperatingScheduleScreenId");

                                    b2.ToTable("Screens");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingScheduleScreenId");
                                });

                            b1.OwnsOne("CCMS.Domain.ValueObjects.DaySchedule", "Sunday", b2 =>
                                {
                                    b2.Property<Guid>("OperatingScheduleScreenId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeSpan>("EndTime")
                                        .HasColumnType("interval");

                                    b2.Property<bool>("IsOperating")
                                        .HasColumnType("boolean");

                                    b2.Property<TimeSpan>("StartTime")
                                        .HasColumnType("interval");

                                    b2.HasKey("OperatingScheduleScreenId");

                                    b2.ToTable("Screens");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingScheduleScreenId");
                                });

                            b1.OwnsOne("CCMS.Domain.ValueObjects.DaySchedule", "Thursday", b2 =>
                                {
                                    b2.Property<Guid>("OperatingScheduleScreenId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeSpan>("EndTime")
                                        .HasColumnType("interval");

                                    b2.Property<bool>("IsOperating")
                                        .HasColumnType("boolean");

                                    b2.Property<TimeSpan>("StartTime")
                                        .HasColumnType("interval");

                                    b2.HasKey("OperatingScheduleScreenId");

                                    b2.ToTable("Screens");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingScheduleScreenId");
                                });

                            b1.OwnsOne("CCMS.Domain.ValueObjects.DaySchedule", "Tuesday", b2 =>
                                {
                                    b2.Property<Guid>("OperatingScheduleScreenId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeSpan>("EndTime")
                                        .HasColumnType("interval");

                                    b2.Property<bool>("IsOperating")
                                        .HasColumnType("boolean");

                                    b2.Property<TimeSpan>("StartTime")
                                        .HasColumnType("interval");

                                    b2.HasKey("OperatingScheduleScreenId");

                                    b2.ToTable("Screens");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingScheduleScreenId");
                                });

                            b1.OwnsOne("CCMS.Domain.ValueObjects.DaySchedule", "Wednesday", b2 =>
                                {
                                    b2.Property<Guid>("OperatingScheduleScreenId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeSpan>("EndTime")
                                        .HasColumnType("interval");

                                    b2.Property<bool>("IsOperating")
                                        .HasColumnType("boolean");

                                    b2.Property<TimeSpan>("StartTime")
                                        .HasColumnType("interval");

                                    b2.HasKey("OperatingScheduleScreenId");

                                    b2.ToTable("Screens");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingScheduleScreenId");
                                });

                            b1.Navigation("Friday")
                                .IsRequired();

                            b1.Navigation("Monday")
                                .IsRequired();

                            b1.Navigation("Saturday")
                                .IsRequired();

                            b1.Navigation("Sunday")
                                .IsRequired();

                            b1.Navigation("Thursday")
                                .IsRequired();

                            b1.Navigation("Tuesday")
                                .IsRequired();

                            b1.Navigation("Wednesday")
                                .IsRequired();
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("CCMS.Domain.Entities.ScreenImage", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.Screen", "Screen")
                        .WithMany("Images")
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.ScreenTagAssignment", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CCMS.Domain.Entities.Screen", "Screen")
                        .WithMany("TagAssignments")
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCMS.Domain.Entities.ScreenTag", "Tag")
                        .WithMany("ScreenAssignments")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Screen");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.SlotAvailability", b =>
                {
                    b.HasOne("CCMS.Domain.Entities.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Impressions");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Creatives");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Creative", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.OwnerContent", b =>
                {
                    b.Navigation("Impressions");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.Screen", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Images");

                    b.Navigation("Impressions");

                    b.Navigation("TagAssignments");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.ScreenTag", b =>
                {
                    b.Navigation("ScreenAssignments");
                });

            modelBuilder.Entity("CCMS.Domain.Entities.User", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("Memberships");

                    b.Navigation("PhoneVerificationOtps");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Screens");
                });
#pragma warning restore 612, 618
        }
    }
}
